# Generated by Django 3.2.5 on 2022-04-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_scheduling_app', '0002_auto_20220330_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
