# Generated by Django 3.2.5 on 2022-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp_scheduling_app', '0004_auto_20220402_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulereportstudent',
            name='schedule_status',
            field=models.IntegerField(default=False),
        ),
    ]
